---
- name: retrieve microkernel and overlays from bintray
  get_url: url="https://bintray.com/artifact/download/rackhd/binary/builds/{{ item }}"
           dest="/home/vagrant/src/on-http/static/http/common/{{ item }}"
           validate_certs=no
           force=yes
  with_items:
   - base.trusty.3.13.0-32-generic.squashfs.img
   - discovery.overlay.cpio.gz
   - initrd.img-3.13.0-32-generic
   - vmlinuz-3.13.0-32-generic

- name: retrieve the latest bootloaders from bintray
  get_url: url="https://bintray.com/artifact/download/rackhd/binary/ipxe/{{ item }}"
           dest="/home/vagrant/src/on-tftp/static/tftp/{{ item }}"
           validate_certs=no
           force=yes
  with_items:
   - monorail.ipxe
   - monorail-efi32-snponly.efi
   - monorail-efi64-snponly.efi
   - undionly.kpxe
